"""Offline authoring source: explicit pixel polygons produce committed binary masks.

No geometry is generated by the runtime renderer. Editing these authored silhouettes
requires rebuilding and reviewing the catalog/contact sheets.
"""
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageChops

ROOT = Path(__file__).resolve().parents[1]/'app/assets/sprites/v1'
ANCHORS = dict(body=[32,41],head=[32,31],ears=[32,17],tail=[40,44],limbs=[32,44],wings=[32,34],horns=[32,16],eyes=[32,24])
parts = {}

def mask(polygons):
    im = Image.new('L',(64,64))
    draw = ImageDraw.Draw(im)
    for poly in polygons:
        draw.polygon(poly,fill=255)
    return im

def add(part,slot,layer,polygons,regions=None,details=None,fragment='main',outline=True):
    occupancy = mask(polygons)
    # Interior is the one-pixel erosion, leaving an authored pixel outline.
    interior = occupancy.copy()
    if outline:
        for dx,dy in [(1,0),(-1,0),(0,1),(0,-1)]:
            shifted=Image.new('L',(64,64))
            shifted.paste(occupancy,(dx,dy))
            interior=ImageChops.darker(interior,shifted)
    roles = {r:Image.new('L',(64,64)) for r in ['base','highlight','accent','shadow','outline']}
    roles['outline']=ImageChops.subtract(occupancy,interior)
    remaining=interior.copy()
    for r,polys in (details or {}).items():
        added=ImageChops.darker(mask(polys),remaining)
        roles[r]=ImageChops.lighter(roles[r],added)
        remaining=ImageChops.subtract(remaining,added)
    roles['base']=remaining
    masks={'occupancy':occupancy,**roles}
    for region,polys in (regions or {}).items():
        masks['region:'+region]=ImageChops.darker(mask(polys),remaining)
    bounds=occupancy.getbbox()
    folder=ROOT/part
    folder.mkdir(parents=True,exist_ok=True)
    files={}
    for role,im in masks.items():
        filename=f'{fragment}_{role.replace(":","_")}.png'
        im.crop(bounds).save(folder/filename)
        files[role]=filename
    entry=parts.setdefault(part,dict(slot=slot,family='biped',pose='front_three_quarter',local_origin=[0,0],fragments=[]))
    anchor=ANCHORS[slot]
    entry['fragments'].append(dict(layer=layer,mask_offset=[bounds[0]-anchor[0],bounds[1]-anchor[1]],masks=files))

def box(x0,y0,x1,y1): return [(x0,y0),(x1,y0),(x1,y1),(x0,y1)]

def main():
    add('compact_torso','body',40,[[(26,30),(37,30),(41,36),(42,46),(38,51),(25,51),(22,46),(23,36)]],{'belly':[box(27,37,36,48)]},{'shadow':[box(38,36,42,51)],'highlight':[box(24,33,27,39)]})
    head_shapes={
      'fox_large_round':[(22,14),(38,14),(44,18),(46,26),(41,31),(35,34),(25,33),(18,28),(17,21)],
      'cat_round':[(22,15),(39,15),(45,20),(46,27),(41,32),(25,34),(19,30),(17,23)],
      'lizard_round':[(24,14),(38,15),(43,20),(43,24),(46,25),(45,30),(39,34),(23,33),(18,28),(17,21)]}
    for part,shape in head_shapes.items():
        add(part,'head',50,[shape],{'head':[box(17,14,46,27)],'muzzle':[box(18,28,45,34)]},{'shadow':[box(42,19,46,34)],'highlight':[box(22,16,28,18)],'outline':[box(31,29,33,30),box(33,31,37,31)]})
    add('paired_tall_triangles','ears',70,[[(18,22),(18,6),(27,17),(26,22)],[(36,20),(43,6),(46,22)]],{'ear_tips':[box(16,6,46,12)]},{'shadow':[box(22,13,25,19),box(42,13,44,19)]})
    add('paired_round_ears','ears',70,[[(17,18),(16,13),(18,9),(23,9),(27,15),(26,20)],[(37,17),(39,10),(44,9),(46,13),(45,21)]],{'ear_tips':[box(16,9,46,13)]})
    add('paired_short_fins','ears',70,[[(18,18),(16,12),(25,18),(24,22)],[(39,19),(46,12),(44,22)]],details={'accent':[box(16,12,46,16)]})
    add('single_fluffy_zigzag','tail',10,[[(39,43),(45,39),(45,34),(50,36),(55,29),(58,37),(54,44),(49,44),(50,49),(44,51),(40,48)]],{'tail_tip':[box(50,29,58,40)]},{'shadow':[box(39,45,50,51)]})
    add('single_cat_curve','tail',10,[[(39,46),(48,46),(52,42),(52,33),(55,29),(58,30),(58,35),(55,35),(55,45),(50,50),(40,51)]],{'tail_tip':[box(52,29,58,35)]})
    add('single_lizard_taper','tail',10,[[(39,42),(45,43),(49,40),(53,36),(58,34),(56,40),(50,47),(43,51),(39,49)]],{'tail_tip':[box(51,34,58,41)]})
    for part in ['short_paws','short_claws']:
        details={'shadow':[box(18,35,23,46)]}
        if part=='short_claws': details['accent']=[box(22,53,28,54),box(36,53,44,54)]
        add(part,'limbs',30,[[(23,35),(19,37),(18,44),(22,46),(25,41)],box(23,48,29,55)],{'paws':[box(24,51,28,54)]} if part=='short_paws' else {},details=details,fragment='far')
        add(part,'limbs',60,[[(40,35),(45,38),(46,44),(42,46),(39,42)],box(35,48,43,55)],{'paws':[box(36,51,42,54)]} if part=='short_paws' else {},details,fragment='near')
    add('paired_small_bat','wings',20,[[(25,32),(17,27),(7,29),(10,40),(15,36),(19,43),(26,39)],[(38,32),(46,27),(56,29),(53,40),(48,36),(44,43),(37,39)]],{'wing_membrane':[box(7,27,26,43),box(37,27,56,43)]})
    add('paired_small_feather','wings',20,[[(25,33),(19,28),(8,27),(7,31),(12,34),(9,36),(16,38),(14,41),(24,43)],[(38,33),(45,28),(55,27),(56,31),(51,34),(54,36),(47,38),(49,41),(39,43)]],{'wing_feathers':[box(7,27,25,43),box(38,27,56,43)]})
    add('single_forehead_horn','horns',80,[[(28,18),(31,8),(34,18)]],{'horns':[box(23,8,39,19)]})
    add('paired_small_horns','horns',80,[[(23,19),(25,9),(29,19)],[(34,19),(37,9),(39,19)]],{'horns':[box(23,8,39,19)]})
    eyes={
       'alert':[box(24,22,28,26),box(36,22,39,25)],
       'gentle':[[(24,24),(25,23),(27,23),(28,24),(28,26),(24,26)],[(36,24),(37,23),(39,24),(39,26),(36,26)]],
       'fierce':[[(24,22),(29,24),(28,27),(24,26)],[(35,24),(40,22),(39,26),(36,27)]]}
    for part,polys in eyes.items():
        add(part,'eyes',90,polys,details={'highlight':[box(25,23,25,23)],'outline':polys},outline=False)
    ROOT.mkdir(parents=True,exist_ok=True)
    (ROOT/'catalog.json').write_text(json.dumps(dict(version='1',renderer_version='1',anchors=ANCHORS,parts=parts),indent=2)+'\n')

if __name__=='__main__': main()
